### ISSUE TITLE
Wheel adds unwanted files to site-packages directory

### ISSUE THREAD

**Issue by jtilly** [altair-viz/sphinxext-altair#4]
With this package, we're running into the same issue as https://github.com/altair-viz/altair/pull/3057. Installing the wheel adds `README.md`, `LICENSE`, `pyproject.toml` to `.env/lib/python3.11/site-packages/`.

**Comment by binste** [comment]
Thank you for reporting it! I'll wait to see how the discussion resolves in https://github.com/altair-viz/altair/pull/3057 and will then apply the same fix here.

**Comment by binste** [comment]
Fix released in version 0.1.1
