### ISSUE TITLE
Keep `pyproject.toml` in sync with `altair`

### ISSUE THREAD

**Issue by dangotbanned** [altair-viz/sphinxext-altair#9]
I think generally this would be desired, but enough of a low-priority item to have been overlooked.

# Motivation
## Reduce docs build time
@binste I did some [investigating](https://github.com/vega/altair/pull/3431/commits/ca961c067506f4a914d1aff3884668489fc57b31) on improving the performance when building the `altair` docs a while back.
I ultimately [reverted](https://github.com/vega/altair/pull/3431/commits/26df622644227d9e309444ad021d8dd2c964eabe) those changes, as that alone had no effect on build time.

`sphinxext_altair` is quite small, but used frequently enough that I think it (if optimized) could speed things up a bit.
At the very least, ruling it out would be helpful, as would any lessons learned (w/ `sphinx`, `docutils`, `jinja2`) during the process when moving back to look at [sphinxext](https://github.com/vega/altair/tree/main/sphinxext).

Applying `ruff` auto-fixes would be an easy starting point for this work

# `pyproject.toml`
## Links
- [`altair`](https://github.com/vega/altair/blob/cfab6601aa649227c20880d05ae27799297694c3/pyproject.toml)
- [`sphinxext_altair`](https://github.com/vega/sphinxext-altair/blob/b937d72f9cb392254380bd529d6d6daa1daac859/pyproject.toml)

## Differences
- Probably won't benefit from *all* of the current `ruff` rules, but would be simple enough to copy over `[tool.ruff.(lint|format)]`
- Usage of `black`
	- Shouldn't be required since `ruff` added a formatter
- python version bounds (also internally inconsistent)
	- https://github.com/vega/sphinxext-altair/blob/b937d72f9cb392254380bd529d6d6daa1daac859/pyproject.toml#L31
	- https://github.com/vega/sphinxext-altair/blob/b937d72f9cb392254380bd529d6d6daa1daac859/pyproject.toml#L104
	- https://github.com/vega/sphinxext-altair/blob/b937d72f9cb392254380bd529d6d6daa1daac859/.github/workflows/lint.yml#L14
	- https://github.com/vega/sphinxext-altair/blob/b937d72f9cb392254380bd529d6d6daa1daac859/pyproject.toml#L91
	- https://github.com/vega/sphinxext-altair/blob/b937d72f9cb392254380bd529d6d6daa1daac859/.github/workflows/build.yml#L10

**Comment by binste** [comment]
Agree! Having some consistency across repos sounds desirable to me as well. And if it gets us closer to speeding up the docs builds, that's very nice :)

**Comment by dangotbanned** [comment]
> Agree! Having some consistency across repos sounds desirable to me as well. And if it gets us closer to speeding up the docs builds, that's very nice :)

Perfect, I'll take a look at this tomorrow

**Comment by dangotbanned** [comment]
@binste what do you think about bumping to `requires-python = ">=3.9"`?

AFAIK we are always building the docs now with (`3.11|3.12`).
I would think downstream users (if any) wouldn't be building docs in multiple `python` versions. 
However if they were, surely it couldn't extend that far back?

Thinking ahead about reducing the maintenance burden - which even in the short term - could mean not needing to revisit in October 2024.

**Comment by binste** [comment]
Thanks for bringing it up! Agree, we can require 3.9. Seems very unlikely that this would hurt someone. Also, the current version works great so one could always fall back on that one.
